### ISSUE TITLE
ansible script to deploy the ethhmy bridge

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/ansible#3]
Please work with @potvik and @gupadhyaya to deploy the ethhmy bridge in system service on an AWS instance.

Better create the instance in mainnet account as it is intended for production.

https://www.notion.so/harmonyone/Internal-Security-Audit-0ec7262ec45947e6bec455121cd5e5c9

**Comment by jhd2best** [comment]
already launched ethhmy bridge manually. next will create Ansible script
