### ISSUE TITLE
crontab to cleanup log once a week

### ISSUE THREAD

**Issue by LeoHChen** [harmony-one/ansible#4]
On mainnet nodes, we can install a crontab to clean up the old log files, based on timestamp, keep the log for one week.
And do the cleanup once a week would be okay.

Please install this crontab on all mainnet nodes, ideally deploy using an ansible script.

remove the latest/*.gz if they are more than 1 week old during the clean up job.

**Comment by jhd2best** [comment]
will user command:
`find /home/ec2-user/latest -name "*.gz" -mtime +1 -type f -exec rm -f {} \;`

**Comment by jhd2best** [comment]
already done in all node

**Comment by jhd2best** [comment]
see PR:https://github.com/harmony-one/ansible/pull/5
